@startuml
class javafx.application.Application
class javafx.collections.FXCollections
class javafx.collections.ObservableList
class javafx.scene.Scene
class javafx.scene.control.Label
class javafx.scene.layout.StackPane
class javafx.stage.Stage
class org.aletane04.Main
class org.aletane04.controller.LibriController
class org.aletane04.controller.MainController
class org.aletane04.controller.PrestitiController
class org.aletane04.controller.UtentiController
class org.aletane04.data.Biblioteca
class org.aletane04.data.BibliotecaFileManager
class org.aletane04.exceptions.LibroNonDisponibileException
class org.aletane04.exceptions.LimitePrestitiSuperatoException
class org.aletane04.model.Libro
class org.aletane04.model.Prestito
class org.aletane04.model.Utente
enum org.aletane04.model.StatoPrestito
interface javafx.fxml.Initializable
org.aletane04.Main --|> javafx.application.Application
org.aletane04.controller.LibriController --|> javafx.fxml.Initializable
org.aletane04.controller.MainController --|> javafx.fxml.Initializable
org.aletane04.controller.PrestitiController --|> javafx.fxml.Initializable
org.aletane04.controller.UtentiController --|> javafx.fxml.Initializable
@enduml